const version = process.env.npm_package_version;
console.log('Hello World-fix1');
console.log('Hello World');
console.log('Hello World');
console.log('Hello World');
console.log('Hello World');
console.log('Hello World');
console.log('Version: ' + version);
console.log('Hello World');
console.log('Hello World');
console.log('Hello World sq1');
console.log('Hello World sq2');
console.log('Hello World sq3');
console.log('Hello World sq-two-1');
console.log('Hello World sq-two-2');
console.log('Hello World sq-two-3');